### ISSUE TITLE
 undefined is not an object (evaluating 'this._pad.socket.json.send')

### ISSUE THREAD

**Issue by vladimirdulov** [ether/ep_webrtc#232]
Hello, 

I'm experiencing some issues with `etherpad-lite` when `ep_webrtc` plugin installed.
This error popup appears on every page reload.

![Screenshot 2024-09-06 at 17 44 09](https://github.com/user-attachments/assets/1e6373f2-7885-4262-b687-09b9583c4e92)

Browser console:
![Screenshot 2024-09-06 at 17 47 35](https://github.com/user-attachments/assets/acbe4613-6cf4-43d4-a544-60e5948f160b)

The logs contains the following errors:
```
Sep 06 17:33:00 [2024-09-06T13:33:00.115] [ERROR] socket.io - Error handling pad message from boa3rb6OvGzmfW1cAAAD: TypeError: Cannot read properties of undefined (reading 'send')
Sep 06 17:33:00 at handleRTCMessage (/run/etherpad-lite/src/plugin_packages/.versions/ep_webrtc@2.3.18/index.js:101:26)
Sep 06 17:33:00 at exports.handleMessage [as hook_fn] (/run/etherpad-lite/src/plugin_packages/.versions/ep_webrtc@2.3.18/index.js:231:5)
Sep 06 17:33:00 at <anonymous> (/run/etherpad-lite/src/static/js/pluginfw/hooks.ts:273:18)
Sep 06 17:33:00 at new Promise (<anonymous>)
Sep 06 17:33:00 at callHookFnAsync (/run/etherpad-lite/src/static/js/pluginfw/hooks.ts:236:16)
Sep 06 17:33:00 at <anonymous> (/run/etherpad-lite/src/static/js/pluginfw/hooks.ts:351:54)
Sep 06 17:33:00 at Array.map (<anonymous>)
Sep 06 17:33:00 at Object.exports.aCallAll (/run/etherpad-lite/src/static/js/pluginfw/hooks.ts:351:13)
Sep 06 17:33:00 at Object.exports.handleMessage (/run/etherpad-lite/src/node/handler/PadMessageHandler.ts:332:20)
Sep 06 17:33:00 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Sep 06 17:33:00 at <anonymous> (/run/etherpad-lite/src/node/handler/SocketIORouter.ts:84:14)
Sep 06 17:33:00 [2024-09-06T13:33:00.119] [ERROR] socket.io - Error handling pad message from boa3rb6OvGzmfW1cAAAD: TypeError: Cannot read properties of undefined (reading 'send')
Sep 06 17:33:00 at handleRTCMessage (/run/etherpad-lite/src/plugin_packages/.versions/ep_webrtc@2.3.18/index.js:101:26)
Sep 06 17:33:00 at exports.handleMessage [as hook_fn] (/run/etherpad-lite/src/plugin_packages/.versions/ep_webrtc@2.3.18/index.js:231:5)
Sep 06 17:33:00 at <anonymous> (/run/etherpad-lite/src/static/js/pluginfw/hooks.ts:273:18)
Sep 06 17:33:00 at new Promise (<anonymous>)
Sep 06 17:33:00 at callHookFnAsync (/run/etherpad-lite/src/static/js/pluginfw/hooks.ts:236:16)
Sep 06 17:33:00 at <anonymous> (/run/etherpad-lite/src/static/js/pluginfw/hooks.ts:351:54)
Sep 06 17:33:00 at Array.map (<anonymous>) <30>1 2024-09-06T13:33:00Z localhost 3fda9a59-7e99-447c-b386-141c12945a6c 1380065 3fda9a59-7e99-447c-b386-141c12945a6c - at Object.exports.aCallAll (/run/etherpad-lite/src/static/js/pluginfw/hooks.ts:351:13) <30>1 2024-09-06T13:33:00Z localhost 3fda9a59-7e99-447c-b386-141c12945a6c 1380065 3fda9a59-7e99-447c-b386-141c12945a6c - at Object.exports.handleMessage (/run/etherpad-lite/src/node/handler/PadMessageHandler.ts:332:20) <30>1 2024-09-06T13:33:00Z localhost 3fda9a59-7e99-447c-b386-141c12945a6c 1380065 3fda9a59-7e99-447c-b386-141c12945a6c - at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Sep 06 17:33:00 at <anonymous> (/run/etherpad-lite/src/node/handler/SocketIORouter.ts:84:14)
Sep 06 17:33:00 [2024-09-06T13:33:00.174] [WARN] client - TypeError: undefined is not an object (evaluating 'this._pad.socket.json.send') -- {
Sep 06 17:33:00 errorId: 'i2HAmYNhm3S3BpeiwEqB',
Sep 06 17:33:00 type: 'Unhandled Promise rejection',
Sep 06 17:33:00 msg: "TypeError: undefined is not an object (evaluating 'this._pad.socket.json.send')",
Sep 06 17:33:00 url: 'https://etherpad-lite.my-domain.net/p/ma0Pulbn9cytNXd-nUSQ',
Sep 06 17:33:00 source: 'unknown',
Sep 06 17:33:00 linenumber: -1,
Sep 06 17:33:00 userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15',
Sep 06 17:33:00 stack: 'sendErrorStat@https://etherpad-lite.my-domain.net/watch/pad:30299:32\n' +
Sep 06 17:33:00 'showUserMediaError@https://etherpad-lite.my-domain.net/watch/pad:29808:33\n' +
Sep 06 17:33:00 '@https://etherpad-lite.my-domain.net/watch/pad:29878:60\n' +
Sep 06 17:33:00 '@https://etherpad-lite.my-domain.net/watch/pad:29878:61'
Sep 06 17:33:00 }
```

`etherpad-lite v2.2.3`
Installed plugins:
```
                wrappy 
                hexoid 
                once 
                underscore 
                lodash 
                asap 
                wrappy 
                dezalgo 
                fast-deep-equal 
                require-from-string 
                punycode 
                uri-js 
                lru-cache 
                ep_align 
                ep_embedded_hyperlinks2 
                ep_font_color 
                ep_headings2 
                ep_markdown 
                ep_openid_connect 
                ep_user_displayname 
                ep_stable_authorid 
                ep_guest 
                ep_comments_page 
                ep_webrtc
```

**Comment by johackim** [comment]
I have the same error with this [docker configuration](https://github.com/ethibox/awesome-stacks/blob/master/stacks/etherpad.yml).

**Comment by SamTV12345** [comment]
Hi I hopefully fixed this issue. I didn't get a mention that the issue was opened. Sorry :(

**Comment by SamTV12345** [comment]
It's published. Please upgrade to v2.5.1
