### ISSUE TITLE
author error - server side logs.

### ISSUE THREAD

**Issue by JohnMcLear** [ether/ep_webrtc#70]
```
Sep 11 11:29:14 host run.sh[13734]: [2020-09-11 11:29:14.872] [ERROR] console - (node:13734) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'author' of undefined
Sep 11 11:29:14 host run.sh[13734]: at handleRTCMessage (/home/etherpad-lite/node_modules/ep_webrtc/index.js:32:40)
Sep 11 11:29:14 host run.sh[13734]: at Object.exports.handleMessage [as hook_fn] (/home/etherpad-lite/node_modules/ep_webrtc/index.js:121:5)
Sep 11 11:29:14 host run.sh[13734]: at normalizedhook (/home/etherpad-lite/src/static/js/pluginfw/hooks.js:38:27)
Sep 11 11:29:14 host run.sh[13734]: at hookCallWrapper (/home/etherpad-lite/src/static/js/pluginfw/hooks.js:44:14)
Sep 11 11:29:14 host run.sh[13734]: at /home/etherpad-lite/src/static/js/pluginfw/hooks.js:108:18
Sep 11 11:29:14 host run.sh[13734]: at Array.map (<anonymous>)
Sep 11 11:29:14 host run.sh[13734]: at aCallAll (/home/etherpad-lite/src/static/js/pluginfw/hooks.js:107:51)
Sep 11 11:29:14 host run.sh[13734]: at /home/etherpad-lite/src/static/js/pluginfw/hooks.js:124:9
Sep 11 11:29:14 host run.sh[13734]: at new Promise (<anonymous>)
Sep 11 11:29:14 host run.sh[13734]: at Object.exports.aCallAll (/home/etherpad-lite/src/static/js/pluginfw/hooks.js:123:14)
Sep 11 11:29:14 host run.sh[13734]: at handleMessageHook (/home/etherpad-lite/src/node/handler/PadMessageHandler.js:217:28)
Sep 11 11:29:14 host run.sh[13734]: at runMicrotasks (<anonymous>)
Sep 11 11:29:14 host run.sh[13734]: at processTicksAndRejections (internal/process/task_queues.js:97:5)
Sep 11 11:29:14 host run.sh[13734]: at async Object.exports.handleMessage (/home/etherpad-lite/src/node/handler/PadMessageHandler.js:262:21)
```

cc @orblivion 

I am not sure how to replicate this bug.

**Comment by orblivion** [comment]
I think it's here: https://github.com/ether/ep_webrtc/blob/master/index.js#L33 I guess one of the sessions is undefined. How did you trigger it in the first place? Did it only happen once?

**Comment by JohnMcLear** [comment]
I didn't trigger it, I spotted it on the server side not the client side.  So no idea ;\

**Comment by orblivion** [comment]
Okay, and only once ever?

**Comment by rhansen** [comment]
This should be fixed.
